name: "Format Code"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Install and run clang-format
        run: |
          npm install clang-format
          clang-format-diff-10 -i --style=file

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 🎨 Formattede code
          branch: ${{ github.head_ref }}
