name: "Format Code"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run clang-format
        uses: purduesigbots/clang-format-action@1.0.2
        # use one of clang-format's supported styles or leave this out to use the style in your .clang-format file
        with:
          style: file

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 🎨 Formattede code
          branch: ${{ github.head_ref }}
