name: "Format Code"

on:
  pull_request:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Install clang-format
        run: npm install clang-format

      - name: Run clang format
        run: clang-format-diff-10 -i -style=file */*.c*

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 🎨 Formattede code
          branch: ${{ github.head_ref }}
